export const dummyQuestions = [
  {
    _id: "q1",
    question: "What is the capital of India?",
    testId: "t1",
    options: [
      { name: "Mumbai", answer: false },
      { name: "Delhi", answer: true },
      { name: "Kolkata", answer: false },
      { name: "Chennai", answer: false },
    ],
    correctAns: "Delhi",
    explaination: "Delhi is the capital of India.",
    isDeleted: false,
    attempt: [],
  },
  {
    _id: "q2",
    question: "What is 2 + 2?",
    testId: "t1",
    options: [
      { name: "3", answer: false },
      { name: "4", answer: true },
      { name: "5", answer: false },
      { name: "6", answer: false },
    ],
    correctAns: "4",
    explaination: "2 + 2 equals 4.",
    isDeleted: false,
    attempt: [],
  },
  {
    _id: "q3",
    question: "Which planet is known as the Red Planet?",
    testId: "t1",
    options: [
      { name: "Earth", answer: false },
      { name: "Mars", answer: true },
      { name: "Venus", answer: false },
      { name: "Jupiter", answer: false },
    ],
    correctAns: "Mars",
    explaination: "Mars is known as the Red Planet.",
    isDeleted: false,
    attempt: [],
  },
  {
    _id: "q4",
    question: "Who wrote 'Hamlet'?",
    testId: "t1",
    options: [
      { name: "William Shakespeare", answer: true },
      { name: "Charles Dickens", answer: false },
      { name: "Jane Austen", answer: false },
      { name: "Mark Twain", answer: false },
    ],
    correctAns: "William Shakespeare",
    explaination: "'Hamlet' was written by Shakespeare.",
    isDeleted: false,
    attempt: [],
  },
  {
    _id: "q5",
    question: "What is the boiling point of water?",
    testId: "t1",
    options: [
      { name: "90°C", answer: false },
      { name: "100°C", answer: true },
      { name: "80°C", answer: false },
      { name: "120°C", answer: false },
    ],
    correctAns: "100°C",
    explaination: "Water boils at 100 degrees Celsius.",
    isDeleted: false,
    attempt: [],
  },
  {
    _id: "q6",
    question: "What is the square root of 49?",
    testId: "t2",
    options: [
      { name: "5", answer: false },
      { name: "6", answer: false },
      { name: "7", answer: true },
      { name: "8", answer: false },
    ],
    correctAns: "7",
    explaination: "7 x 7 = 49.",
    isDeleted: false,
    attempt: [],
  },
  {
    _id: "q7",
    question: "What gas do plants absorb from the atmosphere?",
    testId: "t2",
    options: [
      { name: "Oxygen", answer: false },
      { name: "Nitrogen", answer: false },
      { name: "Carbon Dioxide", answer: true },
      { name: "Hydrogen", answer: false },
    ],
    correctAns: "Carbon Dioxide",
    explaination: "Photosynthesis uses CO₂.",
    isDeleted: false,
    attempt: [],
  },
  {
    _id: "q8",
    question: "What is the chemical symbol for water?",
    testId: "t2",
    options: [
      { name: "O2", answer: false },
      { name: "H2O", answer: true },
      { name: "CO2", answer: false },
      { name: "NaCl", answer: false },
    ],
    correctAns: "H2O",
    explaination: "H₂O is water.",
    isDeleted: false,
    attempt: [],
  },
  {
    _id: "q9",
    question: "Who discovered gravity?",
    testId: "t2",
    options: [
      { name: "Albert Einstein", answer: false },
      { name: "Isaac Newton", answer: true },
      { name: "Galileo", answer: false },
      { name: "Kepler", answer: false },
    ],
    correctAns: "Isaac Newton",
    explaination: "Newton discovered gravity under an apple tree.",
    isDeleted: false,
    attempt: [],
  },
  {
    _id: "q10",
    question: "Which is the largest ocean?",
    testId: "t2",
    options: [
      { name: "Atlantic", answer: false },
      { name: "Pacific", answer: true },
      { name: "Indian", answer: false },
      { name: "Arctic", answer: false },
    ],
    correctAns: "Pacific",
    explaination: "The Pacific Ocean is the largest.",
    isDeleted: false,
    attempt: [],
  },
  {
    _id: "q11",
    question: "Which metal is liquid at room temperature?",
    testId: "t3",
    options: [
      { name: "Iron", answer: false },
      { name: "Mercury", answer: true },
      { name: "Copper", answer: false },
      { name: "Gold", answer: false },
    ],
    correctAns: "Mercury",
    explaination: "Mercury is the only liquid metal at room temp.",
    isDeleted: false,
    attempt: [],
  },
  {
    _id: "q12",
    question: "Which language is used to build web apps?",
    testId: "t3",
    options: [
      { name: "HTML", answer: true },
      { name: "C", answer: false },
      { name: "Python", answer: false },
      { name: "SQL", answer: false },
    ],
    correctAns: "HTML",
    explaination: "HTML structures web content.",
    isDeleted: false,
    attempt: [],
  },
  {
    _id: "q13",
    question: "Which country is famous for Eiffel Tower?",
    testId: "t3",
    options: [
      { name: "Italy", answer: false },
      { name: "France", answer: true },
      { name: "Germany", answer: false },
      { name: "USA", answer: false },
    ],
    correctAns: "France",
    explaination: "Eiffel Tower is in Paris, France.",
    isDeleted: false,
    attempt: [],
  },
  {
    _id: "q14",
    question: "What is the freezing point of water?",
    testId: "t3",
    options: [
      { name: "0°C", answer: true },
      { name: "10°C", answer: false },
      { name: "5°C", answer: false },
      { name: "-5°C", answer: false },
    ],
    correctAns: "0°C",
    explaination: "Water freezes at 0°C.",
    isDeleted: false,
    attempt: [],
  },
  {
    _id: "q15",
    question: "How many continents are there?",
    testId: "t3",
    options: [
      { name: "5", answer: false },
      { name: "6", answer: false },
      { name: "7", answer: true },
      { name: "8", answer: false },
    ],
    correctAns: "7",
    explaination: "There are 7 continents.",
    isDeleted: false,
    attempt: [],
  },
  {
    _id: "q16",
    question: "What color do you get when you mix red and white?",
    testId: "t4",
    options: [
      { name: "Pink", answer: true },
      { name: "Orange", answer: false },
      { name: "Brown", answer: false },
      { name: "Purple", answer: false },
    ],
    correctAns: "Pink",
    explaination: "Red + white = pink.",
    isDeleted: false,
    attempt: [],
  },
  {
    _id: "q17",
    question: "How many hours are there in a day?",
    testId: "t4",
    options: [
      { name: "12", answer: false },
      { name: "24", answer: true },
      { name: "36", answer: false },
      { name: "48", answer: false },
    ],
    correctAns: "24",
    explaination: "A day has 24 hours.",
    isDeleted: false,
    attempt: [],
  },
  {
    _id: "q18",
    question: "Which fruit is yellow and long?",
    testId: "t4",
    options: [
      { name: "Apple", answer: false },
      { name: "Banana", answer: true },
      { name: "Grapes", answer: false },
      { name: "Pineapple", answer: false },
    ],
    correctAns: "Banana",
    explaination: "Banana is yellow and long.",
    isDeleted: false,
    attempt: [],
  },
  {
    _id: "q19",
    question: "Which is the smallest prime number?",
    testId: "t4",
    options: [
      { name: "1", answer: false },
      { name: "2", answer: true },
      { name: "3", answer: false },
      { name: "5", answer: false },
    ],
    correctAns: "2",
    explaination: "2 is the smallest prime number.",
    isDeleted: false,
    attempt: [],
  },
  {
    _id: "q20",
    question: "Which body part pumps blood?",
    testId: "t4",
    options: [
      { name: "Lungs", answer: false },
      { name: "Heart", answer: true },
      { name: "Brain", answer: false },
      { name: "Liver", answer: false },
    ],
    correctAns: "Heart",
    explaination: "The heart pumps blood.",
    isDeleted: false,
    attempt: [],
  },
];
